services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /Users/ms/dev/cert/automated/tmp/server_with_chain.crt:/etc/nginx/certs/server.crt
      - /Users/ms/dev/cert/automated/tmp/server.key:/etc/nginx/certs/server.key
    ports:
      - "443:443"